[build]
# Default builder is Railpack; explicit declaration is optional
builder = "RAILPACK"
# Only trigger builds when server files change (helpful in monorepos)
watchPatterns = [
  "src/**",
  "package.json",
  "tsconfig.json",
  "tsconfig.build.json"
]
# Compile TypeScript to dist/ (force install dev deps so tsc is available)
buildCommand = "npm ci --include=dev && node ./node_modules/typescript/bin/tsc -p tsconfig.build.json"

[deploy]
# Start the compiled NestJS app
startCommand = "node dist/main.js"
healthcheckPath = "/health"
